export const products = [
  {
    id: "6ffbf875-39d0-4f53-917a-083a6a9d1cc9",
    title: "Graphic T-shirt",
    price: 72,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "jeans",
    category: "T-shirts",
    colors: ["white", "dark blue", "purple"],
    sizes: ["large", "x-large", "x-small", "large", "4x-large", "large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "d304a8fe-a099-4016-a511-1f2873571361",
    title: "Zip-up Hoodie",
    price: 66,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "hoodie",
    category: "T-shirts",
    colors: ["green", "green", "pink"],
    sizes: ["4x-large", "small", "xx-small", "xx-small", "x-small", "xx-small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "06c65ad5-16b5-442b-b976-d0f67f8d74af",
    title: "Graphic T-shirt",
    price: 77,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "pants",
    category: "Hoodies",
    colors: ["pink", "purple"],
    sizes: ["medium", "small", "small", "xx-small", "3x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "42204ce3-1247-4929-a069-38812a95bbac",
    title: "Slim Fit Jeans",
    price: 69,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "shirt",
    category: "Shorts",
    colors: ["dark blue", "white"],
    sizes: ["medium", "3x-large", "x-small", "x-large", "x-small", "x-small"],
  },
  {
    id: "038fe6a2-6dc7-48d7-962e-b017fb2de28b",
    title: "Slim Fit Jeans",
    price: 25,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "hoodie",
    category: "T-shirts",
    colors: ["light blue", "green", "green", "pink"],
    sizes: ["x-small", "x-small", "x-small", "x-small"],
  },
  {
    id: "6929aa94-ac34-42a6-959d-227e51d17583",
    title: "T-shirt with Tape Details",
    price: 62,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "hoodie",
    category: "Hoodies",
    colors: ["yellow", "purple", "light blue"],
    sizes: ["xx-large", "xx-small", "x-large", "small"],
  },
  {
    id: "e888fabe-d96c-42f6-86f5-0696dd8c9eaa",
    title: "Zip-up Hoodie",
    price: 34,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "jeans",
    category: "Shirts",
    colors: ["black", "pink", "purple"],
    sizes: ["xx-small", "3x-large", "x-small"],
  },
  {
    id: "d68f1aeb-a275-454b-98d7-31221c36d0ba",
    title: "Hoodie with Logo Print",
    price: 23,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "hoodie",
    category: "T-shirts",
    colors: ["white", "red"],
    sizes: ["4x-large", "large", "4x-large", "xx-small", "xx-large"],
  },
  {
    id: "6b603c76-79ae-4635-a7ca-a452cf9668c8",
    title: "Graphic T-shirt",
    price: 73,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "hoodie",
    category: "Pants",
    colors: ["red", "white"],
    sizes: ["4x-large", "large", "3x-large"],
  },
  {
    id: "5261a4ec-7d5c-4ffa-adba-712647b626cd",
    title: "Cargo Pants",
    price: 10,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "pants",
    category: "Pants",
    colors: ["light blue", "light blue", "purple"],
    sizes: ["xx-small", "4x-large", "xx-small", "medium"],
  },
  {
    id: "993623e8-2506-4685-a7aa-caf0ad26f32c",
    title: "Hoodie with Logo Print",
    price: 88,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "t-shirt",
    category: "Pants",
    colors: ["dark blue", "pink"],
    sizes: ["3x-large", "medium", "3x-large"],
  },
  {
    id: "9c58da6c-0102-4f81-9c23-edfb71888d29",
    title: "Zip-up Hoodie",
    price: 34,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "t-shirt",
    category: "T-shirts",
    colors: ["pink", "light blue"],
    sizes: ["x-small", "3x-large", "small", "xx-large", "large"],
  },
  {
    id: "ca1e777b-3f01-4dcd-881a-67b2546db61c",
    title: "Zip-up Hoodie",
    price: 11,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "hoodie",
    category: "T-shirts",
    colors: ["black", "pink", "black"],
    sizes: ["x-small", "medium", "medium", "3x-large", "x-small"],
  },
  {
    id: "4fc2431e-e163-4efd-b746-689b7dd0a5fb",
    title: "T-shirt with Tape Details",
    price: 81,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "shirt",
    category: "Shorts",
    colors: ["green", "purple", "dark blue"],
    sizes: ["xx-large", "large", "small", "4x-large", "xx-small", "x-small"],
  },
  {
    id: "4f907cee-78f5-400f-a884-8bf7bd11ce94",
    title: "Zip-up Hoodie",
    price: 38,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "t-shirt",
    category: "Shorts",
    colors: ["red", "light blue", "yellow"],
    sizes: ["3x-large", "xx-small", "x-large", "xx-large", "x-small"],
  },
  {
    id: "1f99778d-f8a6-4e18-b32f-0b296fb3dc05",
    title: "Hoodie with Logo Print",
    price: 49,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "jeans",
    category: "Shirts",
    colors: ["yellow", "orange"],
    sizes: ["x-large", "4x-large", "small", "small", "xx-large", "xx-large"],
  },
  {
    id: "ef07a66d-88d2-4544-a39d-28b95257e020",
    title: "Hoodie with Logo Print",
    price: 10,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "jeans",
    category: "Pants",
    colors: ["dark blue", "purple"],
    sizes: ["4x-large", "medium", "large", "xx-small"],
  },
  {
    id: "f8c7ce21-75b7-4727-ba9b-8003f2a8263e",
    title: "Zip-up Hoodie",
    price: 95,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "t-shirt",
    category: "Hoodies",
    colors: ["yellow", "purple", "white", "black"],
    sizes: ["4x-large", "xx-small", "3x-large"],
  },
  {
    id: "83392ac1-5b0f-4fb2-8297-25d3369ee52c",
    title: "Cargo Pants",
    price: 48,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "pants",
    category: "Shorts",
    colors: ["yellow", "yellow", "red", "white"],
    sizes: ["large", "small", "x-small", "3x-large", "4x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "0c0a8edf-14db-43f8-a04e-7d84a2f75caf",
    title: "Cargo Pants",
    price: 44,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "hoodie",
    category: "T-shirts",
    colors: ["light blue", "yellow"],
    sizes: ["small", "xx-small", "x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "f56ae062-cd12-4ddc-bab3-5e3b8588fb03",
    title: "Zip-up Hoodie",
    price: 97,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "shirt",
    category: "Hoodies",
    colors: ["orange", "pink"],
    sizes: ["3x-large", "small", "large", "medium"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "f7bac735-6f2f-4573-9177-5e420dcd642a",
    title: "Zip-up Hoodie",
    price: 34,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "hoodie",
    category: "Pants",
    colors: ["black", "black", "pink"],
    sizes: ["4x-large", "4x-large", "x-large", "xx-large", "x-small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "0001a184-60e3-480e-86f5-f477b774c44e",
    title: "Zip-up Hoodie",
    price: 76,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "t-shirt",
    category: "Hoodies",
    colors: ["red", "white", "purple"],
    sizes: ["xx-large", "4x-large", "x-small", "small", "xx-small", "large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "898b3ec3-de9f-440f-ae4d-b25e252be8d6",
    title: "Zip-up Hoodie",
    price: 70,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "pants",
    category: "T-shirts",
    colors: ["green", "orange"],
    sizes: ["x-small", "3x-large", "x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "67d20af6-eece-455f-9332-8b634471d10d",
    title: "Zip-up Hoodie",
    price: 96,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "shirt",
    category: "T-shirts",
    colors: ["light blue", "red", "black", "yellow"],
    sizes: ["large", "x-small", "large", "xx-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "df48de39-e73d-4074-8a19-741acabdd995",
    title: "Slim Fit Jeans",
    price: 73,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "t-shirt",
    category: "Shirts",
    colors: ["orange", "black"],
    sizes: ["large", "medium", "medium", "xx-large", "medium", "x-small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "86311783-c1d0-4294-8108-7c976a795dae",
    title: "Slim Fit Jeans",
    price: 5,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "hoodie",
    category: "T-shirts",
    colors: ["light blue", "pink", "black", "orange"],
    sizes: ["large", "medium", "large", "large", "large", "xx-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "c21fc328-2a5b-4932-b047-124c2fd99ba9",
    title: "Zip-up Hoodie",
    price: 79,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "pants",
    category: "Hoodies",
    colors: ["green", "light blue", "white", "white"],
    sizes: [
      "xx-small",
      "3x-large",
      "4x-large",
      "medium",
      "3x-large",
      "3x-large",
    ],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "4580aef8-23b9-4477-9513-a5c99937f52c",
    title: "Zip-up Hoodie",
    price: 25,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "shirt",
    category: "Pants",
    colors: ["purple", "red"],
    sizes: ["3x-large", "small", "small", "xx-small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "61d3b7a7-f7d7-4801-be51-d3dc9d34b00d",
    title: "Cargo Pants",
    price: 5,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "jeans",
    category: "Shirts",
    colors: ["red", "black"],
    sizes: ["small", "3x-large", "small", "3x-large", "medium", "3x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "16c1723d-1350-4746-9ada-582a8f48a96a",
    title: "Slim Fit Jeans",
    price: 81,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "hoodie",
    category: "Pants",
    colors: ["white", "dark blue"],
    sizes: ["x-small", "xx-small", "medium"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "43b3ba80-6821-49bd-8fae-569b1e3e1e6f",
    title: "Cargo Pants",
    price: 60,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "pants",
    category: "T-shirts",
    colors: ["green", "black"],
    sizes: ["xx-large", "3x-large", "small", "4x-large", "large", "x-small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "abb86f9e-8296-4d6c-a7d5-a5c2f088e942",
    title: "Slim Fit Jeans",
    price: 37,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "jeans",
    category: "Shirts",
    colors: ["dark blue", "orange", "orange", "white"],
    sizes: ["x-small", "medium", "xx-small", "medium"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "26461921-ae03-4780-8178-deac45bcf65b",
    title: "Graphic T-shirt",
    price: 91,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "t-shirt",
    category: "Shirts",
    colors: ["orange", "light blue", "purple"],
    sizes: ["small", "xx-small", "3x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "573c8437-203c-4b3c-a6b9-a0a004bf7a0a",
    title: "T-shirt with Tape Details",
    price: 75,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "jeans",
    category: "Hoodies",
    colors: ["purple", "purple", "black", "green"],
    sizes: ["small", "xx-large", "3x-large", "x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "f22d0864-ec56-48d3-b2ce-81aec73daa30",
    title: "Slim Fit Jeans",
    price: 87,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "hoodie",
    category: "T-shirts",
    colors: ["purple", "white"],
    sizes: ["xx-large", "small", "small", "x-large", "3x-large", "x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "aefeef1e-7088-42a6-89aa-b549e92a4648",
    title: "Hoodie with Logo Print",
    price: 76,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "jeans",
    category: "Shirts",
    colors: ["dark blue", "orange", "black", "red"],
    sizes: ["medium", "4x-large", "x-small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "9300a8d1-3576-45be-aa04-ae071512a653",
    title: "Cargo Pants",
    price: 75,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "shirt",
    category: "Shirts",
    colors: ["light blue", "pink"],
    sizes: ["small", "x-large", "medium"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "3ff4a61f-5577-42e5-a760-bda9d1adec63",
    title: "Graphic T-shirt",
    price: 19,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "t-shirt",
    category: "T-shirts",
    colors: ["pink", "dark blue", "purple", "red"],
    sizes: ["large", "xx-large", "large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "f6ddadfb-2bb9-41d8-a421-e14eca565451",
    title: "Zip-up Hoodie",
    price: 30,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "shirt",
    category: "Shorts",
    colors: ["black", "green", "purple"],
    sizes: ["medium", "medium", "medium"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "0fe0cb9a-5e50-449d-81c3-c828d07f2cc5",
    title: "Hoodie with Logo Print",
    price: 16,
    imageSrc: "/png/shirts/stripes.png",
    imageAlt: "t-shirt",
    category: "Pants",
    colors: ["orange", "light blue"],
    sizes: ["x-large", "x-large", "small", "xx-small", "medium", "large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "6632e045-b1c4-4a7f-b42e-b9bc9ddbfe82",
    title: "Graphic T-shirt",
    price: 20,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "shirt",
    category: "T-shirts",
    colors: ["purple", "pink", "purple"],
    sizes: ["xx-large", "small", "large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "10045159-bd6c-44ef-a49a-abc34ee30214",
    title: "Zip-up Hoodie",
    price: 8,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "jeans",
    category: "Pants",
    colors: ["light blue", "dark blue", "pink"],
    sizes: ["small", "x-large", "medium", "xx-large", "small", "x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "35ac5df1-01d5-4235-850e-6b518c93bdd1",
    title: "Cargo Pants",
    price: 59,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "jeans",
    category: "Shorts",
    colors: ["yellow", "green", "yellow", "orange"],
    sizes: ["3x-large", "small", "x-small", "x-small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "d028e171-0cff-4b1b-a245-66260c6db137",
    title: "T-shirt with Tape Details",
    price: 82,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "pants",
    category: "Pants",
    colors: ["orange", "white", "pink", "light blue"],
    sizes: ["x-small", "4x-large", "small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "f9378146-5c38-4168-bb3b-a1b247bbc4cc",
    title: "Hoodie with Logo Print",
    price: 38,
    imageSrc: "/png/shirts/peach.png",
    imageAlt: "hoodie",
    category: "Pants",
    colors: ["red", "black", "purple", "black"],
    sizes: ["large", "x-small", "xx-large", "4x-large", "small", "large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "4e295808-0c48-4eda-90b5-dbae7dd8c549",
    title: "Slim Fit Jeans",
    price: 31,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "pants",
    category: "Shirts",
    colors: ["pink", "dark blue", "orange", "white"],
    sizes: ["x-large", "medium", "large", "3x-large", "4x-large", "medium"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "f1579184-877c-46d6-9c1a-97dd2738360d",
    title: "Slim Fit Jeans",
    price: 28,
    imageSrc: "/png/shirts/tgreen.png",
    imageAlt: "t-shirt",
    category: "Pants",
    colors: ["dark blue", "dark blue"],
    sizes: ["xx-large", "3x-large", "large", "x-large"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "b5bb4ac2-95fe-4817-a859-df33979ec7d7",
    title: "Cargo Pants",
    price: 53,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "pants",
    category: "Shirts",
    colors: ["yellow", "pink", "pink"],
    sizes: ["small", "4x-large", "xx-large", "4x-large", "3x-large", "small"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
  {
    id: "03079ed8-a9e4-4cc7-b1ec-8500173e845a",
    title: "Slim Fit Jeans",
    price: 33,
    imageSrc: "/png/shirts/black.png",
    imageAlt: "t-shirt",
    category: "Hoodies",
    colors: ["red", "purple", "dark blue"],
    sizes: ["small", "large", "3x-large", "small", "xx-small", "medium"],
    imageSrcs: [
      "/png/front.png",
      "/png/back.png",
      "/png/model.png",
      "/png/close.png",
    ],
    shipping: {
      fee: "Not free",
      discount: "50%",
      deliveryTime: "3-5 working days",
      estimated: "April 20th - 24th, 2025",
    },
  },
];
